# name: deploy
# # 触发工作流程的事件
# on:
#   push:
#     branches:
#       - main
#       - prd
# # 按顺序运行作业
# jobs:
#   #任务ID
#   deploy:
#     runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
#     steps: # 自动化步骤
#       #任务名称
#       - name: auto push
#         uses: Yikun/hub-mirror-action@master # 第一步，下载代码仓库
#         with:
#           src: github/CodesJoker # 源项目github账号\CodesJoker\git1\security
#           dst: github/zerowolf001 # push目标账户
#           dst_key: ${{secrets.ZF_PRIVATE_KEY}} # ssh私钥
#           dst_token: ${{secrets.ZF_ACCESS_TOKEN}} #API TOKEN
#           force_update: true
#           # mappings: "git1=>git2"
#           # static_list: "hub-mirror-action" #不会动态获取源端github/Yikun的repos，仅同步hub-mirror-action这个repo


name: deplay
on:
  push: 
    branches: 
      - main
# 按顺序运行作业
jobs: 
#任务ID
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本3
    steps: 
      - name: 检出本地代码
        uses: actions/checkout@v3
      - name: 同步代码
        run: |
          git config user.name CodesJoker
          git config user.email 2983937743@qq.com
          git remote set-url --push origin git@github.com:CodesJoker/git2.git
          git push -f