name: deploy
# 触发工作流程的事件
on:
  push:
    branches:
      - main
# 按顺序运行作业
jobs:
  #任务ID
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps: # 自动化步骤
      #任务名称
      - name: mirror push
          - uses: actions/checkout@v3 # 第一步，下载代码仓库
          - name: Deploy to Server    # 第二步，推文件到服务器
              env: 
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}