name: deploy
# 触发工作流程的事件
on:
  push:
    branches:
      - main
# 按顺序运行作业
jobs:
  #任务ID
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps: # 自动化步骤
      #任务名称
      - name: auto push
          - uses: Yikun/hub-mirror-action@master # 第一步，下载代码仓库
            with:
            src: github/CodesJoker
            dst: github/CodesJoker
            dst_key: ${{secrets.PRIVATE_KEY}}
            dst_token: ${{secrets.ACCESS_TOKEN}}
            force_update: true
            mappings: "git1=>git2"